# Copyright 2025 syzkaller project authors. All rights reserved.
# Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporter-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reporter-server
  template:
    metadata:
      labels:
        app: reporter-server
    spec:
      serviceAccountName: gke-service-ksa
      containers:
      - name: reporter-image
        image: ${IMAGE_PREFIX}reporter-server:${IMAGE_TAG}
        envFrom:
          - configMapRef:
              name: global-config-env
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 2
            memory: 8G
          limits:
            cpu: 4
            memory: 16G
