# Copyright 2025 syzkaller project authors. All rights reserved.
# Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.

resources:
  - rebuild-kernels-cron.yaml
  - triage/workflow-template.yaml
  - build/workflow-template.yaml
  - boot/workflow-template.yaml
  - fuzz/workflow-template.yaml
