# Copyright 2025 syzkaller project authors. All rights reserved.
# Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.

apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
data:
  config.yaml: |
    parallelWorkflows: 5
    loreArchives:
      - netdev
      - linux-ext4
    emailReporting:
      name: test-name
      docs: http://docs/
      supportEmail: name@email.com
