# Copyright 2025 syzkaller project authors. All rights reserved.
# Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.

resources:
  - ../common
  - global-config.yaml
  - global-config-env.yaml
  - kernel-disk-pvc.yaml
  - workflow-artifacts.yaml

# Unlike the minikube environment, GKE Terraform scripts will
# pre-create the service accounts.

patches:
  - target:
      kind: WorkflowTemplate
      name: (boot|fuzz)-step-template
    patch: |-
      - op: replace
        path: /spec/templates/0/tolerations
        value:
            - key: "workload"
              operator: "Equal"
              value: "nested-vm"
              effect: "NoSchedule"
  - target:
      kind: WorkflowTemplate
      name: (boot|fuzz)-step-template
    patch: |-
      - op: replace
        path: /spec/templates/0/nodeSelector
        value:
          cloud.google.com/gke-nodepool: nested-vm-pool
