# Copyright 2025 syzkaller project authors. All rights reserved.
# Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      serviceAccountName: gke-service-ksa
      containers:
      - name: controller-image
        image: ${IMAGE_PREFIX}controller:${IMAGE_TAG}
        envFrom:
          - configMapRef:
              name: global-config-env
        volumeMounts:
          - name: config-volume
            mountPath: /config
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 2
            memory: 8G
          limits:
            cpu: 4
            memory: 16G
      volumes:
        - name: config-volume
          configMap:
            name: global-config
